services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: exreserva-postgres
    environment:
      POSTGRES_DB: exreserva
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    container_name: exreserva-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/exreserva?schema=public
      JWT_SECRET: your-secret-key-change-in-production
      JWT_EXPIRES_IN: 24h
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: yarn dev

  # Frontend App
  frontend:
    build: ./frontend
    container_name: exreserva-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: yarn dev

  # Prisma Studio (Database GUI)
  prisma-studio:
    build: ./backend
    container_name: exreserva-prisma-studio
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/exreserva?schema=public
    ports:
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: yarn db:studio

volumes:
  postgres_data:

networks:
  default:
    name: exreserva-network
