apiVersion: v1
kind: ConfigMap
metadata:
  name: exreserva-config
  namespace: exreserva
data:
  NODE_ENV: "production"
  FRONTEND_URL: "http://localhost:3000"
  JWT_EXPIRES_IN: "24h"
  # Database URL will be set via secret
  # JWT_SECRET will be set via secret
