apiVersion: apps/v1
kind: Deployment
metadata:
  name: exreserva-frontend
  namespace: exreserva
  labels:
    app: exreserva-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exreserva-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: exreserva-frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: exreserva-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://exreserva-backend-service:3001/api"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
