apiVersion: v1
kind: Service
metadata:
  name: exreserva-backend-service
  namespace: exreserva
  labels:
    app: exreserva-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: exreserva-backend
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: exreserva-frontend-service
  namespace: exreserva
  labels:
    app: exreserva-frontend
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    app: exreserva-frontend
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: exreserva
  labels:
    app: postgres
    tier: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: postgres
    tier: database
